# Generated by Django 5.1.4 on 2025-01-12 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='City_name',
        ),
    ]
