# Generated by Django 5.1.4 on 2025-01-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0002_remove_state_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_details',
            name='key_features',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
