# Generated by Django 5.1.4 on 2025-01-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0004_rename_ac_room_details_local_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_details',
            name='disable',
            field=models.BooleanField(default=False),
        ),
    ]
