# Generated by Django 5.1.4 on 2025-01-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0006_remove_room_details_local_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_details',
            name='max_guest',
            field=models.SmallIntegerField(default=3),
        ),
    ]
