# Generated by Django 5.1.4 on 2025-01-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0007_alter_room_details_max_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_details',
            name='max_guest',
        ),
    ]
