# Generated by Django 5.1.4 on 2025-01-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0009_room_details_max_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_details',
            name='no_new',
            field=models.BooleanField(default=False),
        ),
    ]
