# Generated by Django 5.1.4 on 2025-01-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='idproof',
        ),
    ]
