# Generated by Django 5.1.4 on 2025-01-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0008_remove_room_details_max_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_details',
            name='max_guest',
            field=models.SmallIntegerField(default=3),
        ),
    ]
