# Generated by Django 5.1.4 on 2025-01-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0010_room_details_no_new'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room_type',
            unique_together={('residency', 'type_name')},
        ),
        migrations.RemoveField(
            model_name='room_type',
            name='bed_type',
        ),
    ]
