# Generated by Django 5.1.4 on 2025-01-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Booking',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Guest',
            new_name='guest',
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_signature',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
