# Generated by Django 5.1.4 on 2025-01-12 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('working', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proof', models.CharField(max_length=200)),
                ('residency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='working.residency')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_guest', models.SmallIntegerField()),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('booked_on', models.DateField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('room_details', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='working.room_details')),
                ('idproof', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservation.identity')),
            ],
            options={
                'unique_together': {('room_details', 'check_in_date')},
            },
        ),
    ]
