# Generated by Django 5.1.4 on 2025-01-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_booking_booked_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Identity',
        ),
    ]
