# Generated by Django 5.1.4 on 2025-01-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_delete_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.PositiveIntegerField(default=4000),
        ),
    ]
