# Generated by Django 5.1.4 on 2025-01-22 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_alter_booking_payment_status'),
        ('working', '0011_alter_room_type_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_status', 'Successfull')), fields=('room_details', 'check_in_date'), name='unique_booking_confirmed'),
        ),
    ]
