# Generated by Django 5.1.4 on 2025-01-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_booking_payment_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Successfull', 'Successfull'), ('Fail', 'Fail')], default='pending', max_length=20),
        ),
    ]
